name: Microsystems for Ubiquitous Sensing, Intelligence, and communication (MUSIC) Lab at the Southern University of Science and Technology (SUSTech)
permalink: /blog/:year/:month/:day/:title
collections:
  publication:
    output: true
  blog:
    output: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-sitemap
